2021-07-26 11:00:46,156 - app - INFO - Microblog startup!
2021-07-26 11:00:46,260 - app - INFO - Microblog startup!
2021-07-26 11:00:46,260 - app - INFO - Microblog startup!
2021-07-26 11:00:46,291 - app - INFO - Microblog startup!
2021-07-26 11:00:46,291 - app - INFO - Microblog startup!
2021-07-26 11:00:46,291 - app - INFO - Microblog startup!
2021-07-26 11:00:46,317 - app - INFO - Microblog startup!
2021-07-26 11:00:46,317 - app - INFO - Microblog startup!
2021-07-26 11:00:46,317 - app - INFO - Microblog startup!
2021-07-26 11:00:46,317 - app - INFO - Microblog startup!
2021-07-26 15:57:35,568 - app - INFO - Microblog startup!
2021-07-26 15:57:50,749 - app - ERROR - Exception on /unfollow/tom [GET]
Traceback (most recent call last):
  File "c:\users\76868\desktop\flask-tutorial-source-code-singlediego-patch-07\venv\lib\site-packages\flask\app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\76868\desktop\flask-tutorial-source-code-singlediego-patch-07\venv\lib\site-packages\flask\app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\76868\desktop\flask-tutorial-source-code-singlediego-patch-07\venv\lib\site-packages\flask\app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\76868\desktop\flask-tutorial-source-code-singlediego-patch-07\venv\lib\site-packages\flask\app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "c:\users\76868\desktop\flask-tutorial-source-code-singlediego-patch-07\venv\lib\site-packages\flask_login\utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "C:\Users\76868\Desktop\Flask-Tutorial-Source-Code-SingleDiego-patch-07\app\auth\routes.py", line 119, in unfollow
    return redirect(url_for('user', username=username))
  File "c:\users\76868\desktop\flask-tutorial-source-code-singlediego-patch-07\venv\lib\site-packages\flask\helpers.py", line 338, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "c:\users\76868\desktop\flask-tutorial-source-code-singlediego-patch-07\venv\lib\site-packages\flask\helpers.py", line 325, in url_for
    rv = url_adapter.build(
  File "c:\users\76868\desktop\flask-tutorial-source-code-singlediego-patch-07\venv\lib\site-packages\werkzeug\routing.py", line 2305, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.BuildError: Could not build url for endpoint 'user' with values ['username']. Did you mean 'auth.user' instead?
2021-07-26 15:59:13,183 - app - INFO - Microblog startup!
2021-07-26 16:04:33,490 - app - INFO - Microblog startup!
