2021-07-22 10:55:24,740 - app - INFO - Microblog startup!
2021-07-22 11:01:51,160 - app - ERROR - Exception on /edit_profile [POST]
Traceback (most recent call last):
  File "c:\users\76868\desktop\flask-tutorial-source-code-singlediego-patch-07\venv\lib\site-packages\sqlalchemy\engine\base.py", line 1770, in _execute_context
    self.dialect.do_execute(
  File "c:\users\76868\desktop\flask-tutorial-source-code-singlediego-patch-07\venv\lib\site-packages\sqlalchemy\engine\default.py", line 717, in do_execute
    cursor.execute(statement, parameters)
sqlite3.IntegrityError: UNIQUE constraint failed: user.username

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "c:\users\76868\desktop\flask-tutorial-source-code-singlediego-patch-07\venv\lib\site-packages\flask\app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\76868\desktop\flask-tutorial-source-code-singlediego-patch-07\venv\lib\site-packages\flask\app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\76868\desktop\flask-tutorial-source-code-singlediego-patch-07\venv\lib\site-packages\flask\app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\76868\desktop\flask-tutorial-source-code-singlediego-patch-07\venv\lib\site-packages\flask\app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "c:\users\76868\desktop\flask-tutorial-source-code-singlediego-patch-07\venv\lib\site-packages\flask_login\utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "C:\Users\76868\Desktop\Flask-Tutorial-Source-Code-SingleDiego-patch-07\app\auth\routes.py", line 77, in edit_profile
    db.session.commit()
  File "<string>", line 2, in commit
  File "c:\users\76868\desktop\flask-tutorial-source-code-singlediego-patch-07\venv\lib\site-packages\sqlalchemy\orm\session.py", line 1428, in commit
    self._transaction.commit(_to_root=self.future)
  File "c:\users\76868\desktop\flask-tutorial-source-code-singlediego-patch-07\venv\lib\site-packages\sqlalchemy\orm\session.py", line 829, in commit
    self._prepare_impl()
  File "c:\users\76868\desktop\flask-tutorial-source-code-singlediego-patch-07\venv\lib\site-packages\sqlalchemy\orm\session.py", line 808, in _prepare_impl
    self.session.flush()
  File "c:\users\76868\desktop\flask-tutorial-source-code-singlediego-patch-07\venv\lib\site-packages\sqlalchemy\orm\session.py", line 3298, in flush
    self._flush(objects)
  File "c:\users\76868\desktop\flask-tutorial-source-code-singlediego-patch-07\venv\lib\site-packages\sqlalchemy\orm\session.py", line 3438, in _flush
    transaction.rollback(_capture_exception=True)
  File "c:\users\76868\desktop\flask-tutorial-source-code-singlediego-patch-07\venv\lib\site-packages\sqlalchemy\util\langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "c:\users\76868\desktop\flask-tutorial-source-code-singlediego-patch-07\venv\lib\site-packages\sqlalchemy\util\compat.py", line 207, in raise_
    raise exception
  File "c:\users\76868\desktop\flask-tutorial-source-code-singlediego-patch-07\venv\lib\site-packages\sqlalchemy\orm\session.py", line 3398, in _flush
    flush_context.execute()
  File "c:\users\76868\desktop\flask-tutorial-source-code-singlediego-patch-07\venv\lib\site-packages\sqlalchemy\orm\unitofwork.py", line 456, in execute
    rec.execute(self)
  File "c:\users\76868\desktop\flask-tutorial-source-code-singlediego-patch-07\venv\lib\site-packages\sqlalchemy\orm\unitofwork.py", line 630, in execute
    util.preloaded.orm_persistence.save_obj(
  File "c:\users\76868\desktop\flask-tutorial-source-code-singlediego-patch-07\venv\lib\site-packages\sqlalchemy\orm\persistence.py", line 234, in save_obj
    _emit_update_statements(
  File "c:\users\76868\desktop\flask-tutorial-source-code-singlediego-patch-07\venv\lib\site-packages\sqlalchemy\orm\persistence.py", line 998, in _emit_update_statements
    c = connection._execute_20(
  File "c:\users\76868\desktop\flask-tutorial-source-code-singlediego-patch-07\venv\lib\site-packages\sqlalchemy\engine\base.py", line 1582, in _execute_20
    return meth(self, args_10style, kwargs_10style, execution_options)
  File "c:\users\76868\desktop\flask-tutorial-source-code-singlediego-patch-07\venv\lib\site-packages\sqlalchemy\sql\elements.py", line 323, in _execute_on_connection
    return connection._execute_clauseelement(
  File "c:\users\76868\desktop\flask-tutorial-source-code-singlediego-patch-07\venv\lib\site-packages\sqlalchemy\engine\base.py", line 1451, in _execute_clauseelement
    ret = self._execute_context(
  File "c:\users\76868\desktop\flask-tutorial-source-code-singlediego-patch-07\venv\lib\site-packages\sqlalchemy\engine\base.py", line 1813, in _execute_context
    self._handle_dbapi_exception(
  File "c:\users\76868\desktop\flask-tutorial-source-code-singlediego-patch-07\venv\lib\site-packages\sqlalchemy\engine\base.py", line 1994, in _handle_dbapi_exception
    util.raise_(
  File "c:\users\76868\desktop\flask-tutorial-source-code-singlediego-patch-07\venv\lib\site-packages\sqlalchemy\util\compat.py", line 207, in raise_
    raise exception
  File "c:\users\76868\desktop\flask-tutorial-source-code-singlediego-patch-07\venv\lib\site-packages\sqlalchemy\engine\base.py", line 1770, in _execute_context
    self.dialect.do_execute(
  File "c:\users\76868\desktop\flask-tutorial-source-code-singlediego-patch-07\venv\lib\site-packages\sqlalchemy\engine\default.py", line 717, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.IntegrityError: (sqlite3.IntegrityError) UNIQUE constraint failed: user.username
[SQL: UPDATE user SET username=? WHERE user.id = ?]
[parameters: ('tom', 1)]
(Background on this error at: http://sqlalche.me/e/14/gkpj)
2021-07-22 15:38:08,850 - app - INFO - Microblog startup!
2021-07-22 15:38:14,010 - app - ERROR - Exception on /edit_profile [GET]
Traceback (most recent call last):
  File "c:\users\76868\desktop\flask-tutorial-source-code-singlediego-patch-07\venv\lib\site-packages\flask\app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\76868\desktop\flask-tutorial-source-code-singlediego-patch-07\venv\lib\site-packages\flask\app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\76868\desktop\flask-tutorial-source-code-singlediego-patch-07\venv\lib\site-packages\flask\app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\76868\desktop\flask-tutorial-source-code-singlediego-patch-07\venv\lib\site-packages\flask\app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "c:\users\76868\desktop\flask-tutorial-source-code-singlediego-patch-07\venv\lib\site-packages\flask_login\utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "C:\Users\76868\Desktop\Flask-Tutorial-Source-Code-SingleDiego-patch-07\app\auth\routes.py", line 72, in edit_profile
    form = EditProfileForm()
  File "c:\users\76868\desktop\flask-tutorial-source-code-singlediego-patch-07\venv\lib\site-packages\wtforms\form.py", line 208, in __call__
    return type.__call__(cls, *args, **kwargs)
TypeError: __init__() missing 1 required positional argument: 'original_username'
2021-07-22 15:38:19,165 - app - ERROR - Exception on /edit_profile [GET]
Traceback (most recent call last):
  File "c:\users\76868\desktop\flask-tutorial-source-code-singlediego-patch-07\venv\lib\site-packages\flask\app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\76868\desktop\flask-tutorial-source-code-singlediego-patch-07\venv\lib\site-packages\flask\app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\76868\desktop\flask-tutorial-source-code-singlediego-patch-07\venv\lib\site-packages\flask\app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\76868\desktop\flask-tutorial-source-code-singlediego-patch-07\venv\lib\site-packages\flask\app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "c:\users\76868\desktop\flask-tutorial-source-code-singlediego-patch-07\venv\lib\site-packages\flask_login\utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "C:\Users\76868\Desktop\Flask-Tutorial-Source-Code-SingleDiego-patch-07\app\auth\routes.py", line 72, in edit_profile
    form = EditProfileForm()
  File "c:\users\76868\desktop\flask-tutorial-source-code-singlediego-patch-07\venv\lib\site-packages\wtforms\form.py", line 208, in __call__
    return type.__call__(cls, *args, **kwargs)
TypeError: __init__() missing 1 required positional argument: 'original_username'
2021-07-22 15:39:16,156 - app - INFO - Microblog startup!
2021-07-23 12:15:14,806 - app - INFO - Microblog startup!
2021-07-23 13:51:13,255 - app - INFO - Microblog startup!
2021-07-23 13:51:39,649 - app - INFO - Microblog startup!
2021-07-23 23:56:08,481 - app - INFO - Microblog startup!
2021-07-24 16:43:40,004 - app - INFO - Microblog startup!
2021-07-25 14:54:36,916 - app - INFO - Microblog startup!
2021-07-25 16:32:02,450 - app - INFO - Microblog startup!
2021-07-25 16:33:50,860 - app - INFO - Microblog startup!
